// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/todolist/app/task/biz/repository"
	"github.com/crazyfrankie/todolist/app/task/biz/repository/dao"
	"github.com/crazyfrankie/todolist/app/task/biz/service"
	"github.com/crazyfrankie/todolist/app/task/rpc"
	"github.com/crazyfrankie/todolist/app/task/rpc/server"
)

// Injectors from wire.go:

func InitTask() *rpc.Server {
	db := InitDB()
	taskDao := dao.NewTaskDao(db)
	taskRepo := repository.NewTaskRepo(taskDao)
	taskService := service.NewTaskService(taskRepo)
	taskServer := server.NewTaskServer(taskService)
	client := InitRegistry()
	rpcServer := rpc.NewServer(taskServer, client)
	return rpcServer
}
