// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/todolist/app/user/biz/repository"
	"github.com/crazyfrankie/todolist/app/user/biz/repository/dao"
	"github.com/crazyfrankie/todolist/app/user/biz/service"
	"github.com/crazyfrankie/todolist/app/user/rpc"
	"github.com/crazyfrankie/todolist/app/user/rpc/server"
)

// Injectors from wire.go:

func InitUser() *rpc.Server {
	db := InitDB()
	userDao := dao.NewUserDao(db)
	userRepo := repository.NewUserRepo(userDao)
	userService := service.NewUserService(userRepo)
	userServer := server.NewUserServer(userService)
	client := InitRegistry()
	rpcServer := rpc.NewServer(userServer, client)
	return rpcServer
}
