// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/todolist/app/user/biz/repository"
	"github.com/crazyfrankie/todolist/app/user/biz/repository/dao"
	"github.com/crazyfrankie/todolist/app/user/biz/service"
	"github.com/crazyfrankie/todolist/app/user/rpc"
	"github.com/crazyfrankie/todolist/app/user/rpc/server"
	"github.com/crazyfrankie/todolist/app/user/rpc_gen/user"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitUser() *rpc.Server {
	client := InitRegistry()
	db := InitDB()
	userDao := dao.NewUserDao(db)
	userRepo := repository.NewUserRepo(userDao)
	userService := service.NewUserService(userRepo)
	userServer := server.NewUserServer(userService)
	v := registerService(userServer)
	rpcServer := rpc.NewServer(client, v)
	return rpcServer
}

// wire.go:

func registerService(u *server.UserServer) func(grpc.ServiceRegistrar) {
	return func(s grpc.ServiceRegistrar) {
		user.RegisterUserServiceServer(s, u)
	}
}
